import bpy
import os
import sys

# Ensure script directory is in path
script_dir = os.path.dirname(os.path.abspath(__file__))
if script_dir not in sys.path:
    sys.path.append(script_dir)

from scene_init import setup_scene
from terrain_importer import import_dem
from hazard_visualizer import load_and_visualize_hazards
from lander_controller import create_lander_model
from trajectory_importer import load_and_visualize_trajectory
from animation_controller import load_and_animate
from hazard_injection import visualize_hazard_event
from replanning_visualizer import visualize_diversion
from mission_ui import setup_telemetry_ui, register_telemetry_handler

def run_final_hero_scenario():
    """
    Executes the complete M6 independent mock visualization pipeline in Blender.
    This reads the JSON artifacts generated by `scripts/run_m6_demo.py` and 
    builds the entire 3D mission console scene.
    """
    print("==================================================")
    print(" M6 BLENDER MISSION CONSOLE - HERO SCENARIO")
    print("==================================================")
    
    # Paths to generated Python Core artifacts
    base_dir = os.path.join(os.path.dirname(script_dir), "..")
    results_dir = os.path.join(base_dir, "results", "m6_demo")
    
    traj_path = os.path.join(results_dir, "trajectory.json")
    event_path = os.path.join(results_dir, "replan_event.json")
    diversion_path = os.path.join(results_dir, "replanned_trajectory.json")
    
    # 1. Setup Environment
    setup_scene()
    
    # 2. Build Terrain & Hazards (Using default mock generator for DEM/Hazards)
    import_dem()
    load_and_visualize_hazards()
    
    # 3. Create Lander Asset
    lander = create_lander_model("M6_HeroLander")
    
    # 4. Import Primary Trajectory
    load_and_visualize_trajectory(traj_path, "PrimaryTrajectory")
    
    # 5. Animate along Primary Trajectory
    # In a full simulation, we'd stop the animation at the hazard event time,
    # but for visualization, we'll animate it fully to show the original plan.
    end_frame = 250
    if os.path.exists(traj_path):
        # We can animate a ghost lander on the original trajectory to compare
        ghost = create_lander_model("GhostLander")
        mat = bpy.data.materials.new("GhostMat")
        mat.blend_method = 'BLEND'
        mat.use_nodes = True
        mat.node_tree.nodes["Principled BSDF"].inputs["Alpha"].default_value = 0.3
        for obj in ghost.children:
            if obj.type == 'MESH':
                obj.data.materials.clear()
                obj.data.materials.append(mat)
                
        load_and_animate("GhostLander", traj_path)
    
    # 6. Inject Hazard & Diversion
    if os.path.exists(event_path):
        visualize_hazard_event(event_path)
        
    if os.path.exists(diversion_path):
        load_and_visualize_trajectory(diversion_path, "DiversionTrajectory")
        # Animate the actual hero lander on the diversion
        end_frame = load_and_animate("M6_HeroLander", diversion_path)
        
    # 7. Setup UI & Telemetry
    setup_telemetry_ui()
    register_telemetry_handler()
    
    # Set playback range
    bpy.context.scene.frame_start = 1
    if end_frame:
        bpy.context.scene.frame_end = end_frame
        
    print("==================================================")
    print(" SCENE BUILD COMPLETE.")
    print("==================================================")

if __name__ == "__main__":
    run_final_hero_scenario()
